# docker-compose.yml
version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_contraseña
      POSTGRES_DB: minio_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: {}
